Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,14 +25,14 @@ jobs:
       - name: Download and Transform CSV
         run: python combo.py
         env:
-          CSV_URL: ${{ secrets.CSV_URL }} # Use the CSV_URL secret for the environment variable
+          CSV_URL: ${{ secrets.CSV_URL }} # Ensure you've added your distributor's CSV URL as a secret
 
       - name: Commit and push if changes
         run: |
           git config --global user.email "mazzarolli.ai@gmail.com"
           git config --global user.name "Camarolli9979797"
           git add -A
-          git commit -m "Updated CSV" || exit 0   # This command will exit with no error if there's nothing to commit
-          git push
+          git commit -m "Updated CSV" || exit 0   # This won't fail if there's nothing to commit
+          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.MYSECRETKEY }}" push --set-upstream origin main
         env:
-          GITHUB_TOKEN: ${{ secrets.MYSECRETKEY }} # Use the MYSECRETKEY secret for the GitHub token
+          MYSECRETKEY: ${{ secrets.MYSECRETKEY }} # This should be your PAT stored in GitHub Secrets
